import type { Metadata } from "next";

import { Inter as FontSans } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { cn } from "@/lib/utils";
import SideNav from "./_components/SideNav";
import Sidebar from "@/components/Footer";
import Topbar from "@/components/Topbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "react-hot-toast";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Myaimix",
  description: "Get the best Content Generated by ai . ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <NextTopLoader
        color="#F58529" // Initial color for the bar
        initialPosition={0.08}
        crawlSpeed={200}
        height={4} // Increased height for visibility
        crawl={true}
        easing="ease-in-out" // Smooth easing
        speed={300} // Increased speed for dynamic effect
        shadow="0 0 15px rgba(245, 133, 41, 0.6), 0 0 5px rgba(245, 133, 41, 0.4)" // Soft shadow
        template={`<div class="bar" role="bar">
         <div class="peg"></div>
       </div>
       <div class="spinner" role="spinner">
         <div class="spinner-icon"></div>
       </div>`}
        zIndex={1600}
        showAtBottom={false}
      />

      <SideNav />

      <div id="print-area" className=" lg:ml-64 md:ml-[80px] ml-0">
        <Toaster />

        {children}
      </div>
      <Sidebar />
    </ThemeProvider>
  );
}
