import type { Metadata } from "next";

import { Inter as FontSans } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { cn } from "@/lib/utils";
import SideNav from "./_components/SideNav";
import Sidebar from "@/components/Footer";
import Topbar from "@/components/Topbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "react-hot-toast";
import { UpdateStrogeContext } from "../constants/UpdateStrageContext";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Myaimix",
  description: "Get the best Content Generated by ai . ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <NextTopLoader
        initialPosition={0.08}
        crawlSpeed={200}
        height={3}
        crawl={true}
        showSpinner={true}
        easing="ease"
        speed={200}
        shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        template={`
    <div class="bar" role="bar" style="background: linear-gradient(to right, #ff7e5f, #feb47b); transform: translateY(0); transition: transform 0.3s ease;">
      <div class="peg" style="box-shadow: 0 0 10px #ff7e5f, 0 0 5px #feb47b;"></div>
    </div> 
    <div class="spinner" role="spinner">
      <div class="spinner-icon"></div>
    </div>
  `}
        zIndex={1600}
        showAtBottom={false}
      />

      <SideNav />

      <div id="print-area" className=" lg:ml-64 md:ml-[80px] ml-0">
        <Toaster />

        {children}
      </div>
      <Sidebar />
    </ThemeProvider>
  );
}
